services:
  backend:
    build:
      context: ./src  # Set the build context to the src folder
      dockerfile: Dockerfile
    ports:
      - "5011:5011"
    env_file:
      - .env

  frontend:
    build:
      context: ./workout-tracker-frontend  # Path to your frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
